In [1]:
x<-10

In [2]:
print(x)

[1] 10


In [3]:
x<-10

In [4]:
y<-20

In [5]:
x+y

[1] 30

In [6]:
x=10
y=20

In [7]:
x+y

[1] 30

In [8]:
x <- 5/10+20*25

In [9]:
x

[1] 500.5

In [10]:
x<- "Hello, World!"

In [11]:
x

[1] "Hello, World!"

In [12]:
class(x)

[1] "character"

In [13]:
x=10
class(x)

[1] "numeric"

In [14]:
x=10.56
class(x)

[1] "numeric"

In [15]:
x=10/25
class(x)

[1] "numeric"

In [16]:
x=TRUE
class(x)

[1] "logical"

In [17]:
x=10L
class(x)

[1] "integer"

In [18]:
x=10+20i
class(x)

[1] "complex"

In [19]:
x=TRUE
class(x)

[1] "logical"

In [20]:
x="TRUE"
class(x)

[1] "character"

In [21]:
x<- c('red','green',"yellow")

In [22]:
x

[1] "red"    "green"  "yellow"

In [23]:
class(x)

[1] "character"

In [24]:
x[1]

[1] "red"

In [25]:
x[2]

[1] "green"

In [26]:
x[3]

[1] "yellow"

In [27]:
x<- c(1,2,3,4,5)

In [28]:
x

[1] 1 2 3 4 5

In [29]:
x<- c(1,2,3,4,5,"Apple")

In [30]:
x

[1] "1"     "2"     "3"     "4"     "5"     "Apple"

In [31]:
x<- list('red','green',"yellow")

In [32]:
x[1]

[[1]]
[1] "red"

In [33]:
x <- list(c(2,5,3),21.3)
x

[[1]]
[1] 2 5 3

[[2]]
[1] 21.3

In [34]:
x[1][1]

[[1]]
[1] 2 5 3

In [35]:
x[2][1]

[[1]]
[1] 21.3

In [36]:
x <- c(list(2,5,3),21.3)
x

[[1]]
[1] 2

[[2]]
[1] 5

[[3]]
[1] 3

[[4]]
[1] 21.3

In [37]:
x[1][1]

[[1]]
[1] 2

In [38]:
x[2][1]

[[1]]
[1] 5

In [39]:
x[1]

[[1]]
[1] 2

In [40]:
x<-matrix( c('A','B','C','D','E','F'), nrow = 2, ncol = 3)
x

[,1] [,2] [,3]
[1,] A    C    E   
[2,] B    D    F

In [41]:
x<-matrix( c('A','B','C','D','E','F'), nrow = 2, ncol = 3, byrow = FALSE)
x

[,1] [,2] [,3]
[1,] A    C    E   
[2,] B    D    F

In [42]:
a <- array(c('A','B'),dim = c(1,2))
a

[,1] [,2]
[1,] A    B

In [43]:
a <- array(c('A','B'),dim = c(2,1))
a

[,1]
[1,] A   
[2,] B

In [44]:
a <- array(c('A','B'),dim = c(1,2,3))
a

, , 1

     [,1] [,2]
[1,] "A"  "B" 

, , 2

     [,1] [,2]
[1,] "A"  "B" 

, , 3

     [,1] [,2]
[1,] "A"  "B"

In [45]:
a <- array(c('A','B'),dim = c(2,1,5))
a

, , 1

     [,1]
[1,] "A" 
[2,] "B" 

, , 2

     [,1]
[1,] "A" 
[2,] "B" 

, , 3

     [,1]
[1,] "A" 
[2,] "B" 

, , 4

     [,1]
[1,] "A" 
[2,] "B" 

, , 5

     [,1]
[1,] "A" 
[2,] "B"

In [46]:
a <- array(c('A','B'),dim = c(1,2,5))
a

, , 1

     [,1] [,2]
[1,] "A"  "B" 

, , 2

     [,1] [,2]
[1,] "A"  "B" 

, , 3

     [,1] [,2]
[1,] "A"  "B" 

, , 4

     [,1] [,2]
[1,] "A"  "B" 

, , 5

     [,1] [,2]
[1,] "A"  "B"

In [47]:
x <- 2

In [48]:
class(x)

[1] "numeric"

In [49]:
y=as.integer(x)

In [50]:
y

[1] 2

In [51]:
class(y)

[1] "integer"

In [52]:
x <- 2.65

In [53]:
y=as.integer(x)

In [54]:
y

[1] 2

In [55]:
x <- "2"
y=as.integer(x)
y

[1] 2

In [56]:
class(y)

[1] "integer"

In [57]:
x.1=10

In [58]:
x.1

[1] 10

In [59]:
x<- "World"
cat(" Hello ",x,"\n")

 Hello  World 


In [60]:
x

[1] "World"

In [61]:
rm(x)

In [62]:
x

ERROR: ignored