In [1]:
x<- c(1, 2, 3)

In [2]:
x

[1] 1 2 3

In [3]:
class(x[0])

[1] "numeric"

In [4]:
x<- c(1, 2, 3, "Id")

In [5]:
x

[1] "1"  "2"  "3"  "Id"

In [6]:
class(x[0])

[1] "character"

In [7]:
x<- list(1, 2, 3)
x

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

In [8]:
class(x[0])

[1] "list"

In [9]:
x<- list(1, 2, 3, "Id")

In [10]:
x

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] "Id"

In [11]:
class(x[0])

[1] "list"

In [12]:
x<-1.5:7.9

In [13]:
x

[1] 1.5 2.5 3.5 4.5 5.5 6.5 7.5

In [14]:
length(x)

[1] 7

In [15]:
x<-c(5,7,3,5,6,6.2,5,6,7,2,3,5,9,0)
x

[1] 5.0 7.0 3.0 5.0 6.0 6.2 5.0 6.0 7.0 2.0 3.0 5.0 9.0 0.0

In [16]:
sort(x)

[1] 0.0 2.0 3.0 3.0 5.0 5.0 5.0 5.0 6.0 6.0 6.2 7.0 7.0 9.0

In [17]:
sort(x, decreasing = TRUE)

[1] 9.0 7.0 7.0 6.2 6.0 6.0 5.0 5.0 5.0 5.0 3.0 3.0 2.0 0.0

In [18]:
x

[1] 5.0 7.0 3.0 5.0 6.0 6.2 5.0 6.0 7.0 2.0 3.0 5.0 9.0 0.0

In [19]:
x=sort(x)

In [20]:
x

[1] 0.0 2.0 3.0 3.0 5.0 5.0 5.0 5.0 6.0 6.0 6.2 7.0 7.0 9.0

In [21]:
x<- c("Adam", "John", "Joseph")
sort(x)

[1] "Adam"   "John"   "Joseph"

In [22]:
x<-c(5,7,3,5,6,6.2,5,6,7,2,3,5,9,0)
x[1:3]

[1] 5 7 3

In [23]:
x[3:5]

[1] 3 5 6

In [24]:
x[c(1, 3)] 

[1] 5 3

In [25]:
y<-1:4

In [26]:
x[y]

[1] 5 7 3 5

In [27]:
x[c(-1)] 

[1] 7.0 3.0 5.0 6.0 6.2 5.0 6.0 7.0 2.0 3.0 5.0 9.0 0.0

In [28]:
x[c(-1:-3)] 

[1] 5.0 6.0 6.2 5.0 6.0 7.0 2.0 3.0 5.0 9.0 0.0

In [29]:
x[c(-2,-5)]

[1] 5.0 3.0 5.0 6.2 5.0 6.0 7.0 2.0 3.0 5.0 9.0 0.0

In [30]:
x

[1] 5.0 7.0 3.0 5.0 6.0 6.2 5.0 6.0 7.0 2.0 3.0 5.0 9.0 0.0

In [31]:
x[1]<-10

In [32]:
x

[1] 10.0  7.0  3.0  5.0  6.0  6.2  5.0  6.0  7.0  2.0  3.0  5.0  9.0  0.0

In [33]:
x<- rep(c(1,2,3), each = 3)

In [34]:
x

[1] 1 1 1 2 2 2 3 3 3

In [35]:
x<- rep(c(1,2,3), times = 3)
x

[1] 1 2 3 1 2 3 1 2 3

In [36]:
x<- rep(c(1,2,3), times = c(4,2,3))

In [37]:
x

[1] 1 1 1 1 2 2 3 3 3

In [38]:
x<- seq(from = 0, to = 10, by = 2)

In [39]:
x

[1]  0  2  4  6  8 10

In [40]:
x<-seq(1,4,length.out=6)  
x

[1] 1.0 1.6 2.2 2.8 3.4 4.0

In [41]:
x<-c("ID1"=45,"ID2"=55,"ID3"=44)  
x["ID1"]

ID1 
 45

In [42]:
    x<-c(1,2,3,4,5,6)  
    x[c(TRUE,FALSE,TRUE,TRUE,FALSE,TRUE)]  

[1] 1 3 4 6

In [43]:
x<- seq(from = 0, to = 10, by = 2)
y<- seq(from = 0, to = 20, by = 2)

In [44]:
x

[1]  0  2  4  6  8 10

In [45]:
y

[1]  0  2  4  6  8 10 12 14 16 18 20

In [46]:
z<-c(x,y)  
z

[1]  0  2  4  6  8 10  0  2  4  6  8 10 12 14 16 18 20

In [47]:
x+y

Warning message in x + y:
“longer object length is not a multiple of shorter object length”


[1]  0  4  8 12 16 20 12 16 20 24 28

In [48]:
x<- seq(from = 0, to = 10, by = 2)
y<- seq(from = 10, to = 20, by = 2)

In [49]:
x+y

[1] 10 14 18 22 26 30

In [50]:
x*y

[1]   0  24  56  96 144 200

In [51]:
x/y

[1] 0.0000000 0.1666667 0.2857143 0.3750000 0.4444444 0.5000000

In [52]:
x-y

[1] -10 -10 -10 -10 -10 -10

In [53]:
x<- seq(from = 0, to = 10, by = 2)
y<- seq(from = 1, to = 20, by = 1)

In [54]:
x

[1]  0  2  4  6  8 10

In [55]:
y

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [56]:
x[x %in% y] 

[1]  2  4  6  8 10

In [57]:
all(x %in% y)

[1] FALSE

In [58]:
x[y[1]]

[1] 0

In [59]:
x

[1]  0  2  4  6  8 10

In [60]:
x[order(x)] 

[1]  0  2  4  6  8 10

In [61]:
x

[1]  0  2  4  6  8 10

In [62]:
rev(x)

[1] 10  8  6  4  2  0

In [63]:
x<-list("A","B",c(1,2,3,4,5),TRUE,FALSE,45.5,4L)  
print(x)  

[[1]]
[1] "A"

[[2]]
[1] "B"

[[3]]
[1] 1 2 3 4 5

[[4]]
[1] TRUE

[[5]]
[1] FALSE

[[6]]
[1] 45.5

[[7]]
[1] 4



In [64]:
x[[1]]

[1] "A"

In [65]:
x[[3]][1]

[1] 1

In [66]:
x[[3]][3]

[1] 3

In [67]:
x[1]

[[1]]
[1] "A"

In [68]:
x[3]=10

In [69]:
x

[[1]]
[1] "A"

[[2]]
[1] "B"

[[3]]
[1] 10

[[4]]
[1] TRUE

[[5]]
[1] FALSE

[[6]]
[1] 45.5

[[7]]
[1] 4

In [70]:
x=rnorm(5, mean = 0, sd = 1)
x

[1] 0.2425819 0.3357785 1.2117727 0.6764915 0.3912940

In [71]:
x=runif(5, min = 2, max = 10)
x

[1] 3.055682 2.263550 7.967701 4.289718 5.567024

In [72]:
set.seed(5)
x=runif(5, min = 2, max = 10)
x

[1] 3.601716 7.481749 9.335006 4.275196 2.837201

In [73]:
invest <- seq(from = 1, to = 12000, by = 1000)

month <- c("January", "February", "March", "April", "May", "June",
           "July", "August", "September", "October", "November", "December")

In [74]:
month[invest > 7000] 

[1] "August"    "September" "October"   "November"  "December"

In [75]:
month[invest > 7000 | invest<3000] 

[1] "January"   "February"  "March"     "August"    "September" "October"  
[7] "November"  "December"

In [76]:
x<- seq(from = 0, to = 10, by = 2)
y<- seq(from = 0, to = 20, by = 2)

In [77]:
x

[1]  0  2  4  6  8 10

In [78]:
y

[1]  0  2  4  6  8 10 12 14 16 18 20

In [79]:
z=list(x,y)

In [80]:
z

[[1]]
[1]  0  2  4  6  8 10

[[2]]
 [1]  0  2  4  6  8 10 12 14 16 18 20

In [81]:
x<- seq(from = 0, to = 10, by = 2)
2 %in% x

[1] TRUE

In [82]:
x

[1]  0  2  4  6  8 10

In [83]:
x=append(x,15)

In [84]:
x

[1]  0  2  4  6  8 10 15

In [85]:
x=append(x,20, after=2)
x

[1]  0  2 20  4  6  8 10 15

In [86]:
seq(from = 1, to = 90, by = 3)

[1]  1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73
[26] 76 79 82 85 88

In [87]:
length(seq(from = 1, to = 90, by = 3))

[1] 30

In [88]:
x <- matrix(seq(from = 1, to = 90, by = 3), nrow = 5, ncol = 6)
x

[,1] [,2] [,3] [,4] [,5] [,6]
[1,]  1   16   31   46   61   76  
[2,]  4   19   34   49   64   79  
[3,]  7   22   37   52   67   82  
[4,] 10   25   40   55   70   85  
[5,] 13   28   43   58   73   88

In [89]:
x[1, 2]

[1] 16

In [90]:
x[,2]

[1] 16 19 22 25 28

In [91]:
x[c(1,2),] 

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    16   31   46   61   76  
[2,] 4    19   34   49   64   79

In [92]:
x[, c(1,2)]

[,1] [,2]
[1,]  1   16  
[2,]  4   19  
[3,]  7   22  
[4,] 10   25  
[5,] 13   28

In [93]:
x <- matrix(seq(from = 1, to = 90, by = 3), nrow = 5, ncol = 6)
x

[,1] [,2] [,3] [,4] [,5] [,6]
[1,]  1   16   31   46   61   76  
[2,]  4   19   34   49   64   79  
[3,]  7   22   37   52   67   82  
[4,] 10   25   40   55   70   85  
[5,] 13   28   43   58   73   88

In [94]:
y <- matrix(seq(from = 0, to = 89, by = 3), nrow = 5, ncol = 6)
y

[,1] [,2] [,3] [,4] [,5] [,6]
[1,]  0   15   30   45   60   75  
[2,]  3   18   33   48   63   78  
[3,]  6   21   36   51   66   81  
[4,]  9   24   39   54   69   84  
[5,] 12   27   42   57   72   87

In [95]:
z=rbind(x,y)
z

[,1] [,2] [,3] [,4] [,5] [,6]
 [1,]  1   16   31   46   61   76  
 [2,]  4   19   34   49   64   79  
 [3,]  7   22   37   52   67   82  
 [4,] 10   25   40   55   70   85  
 [5,] 13   28   43   58   73   88  
 [6,]  0   15   30   45   60   75  
 [7,]  3   18   33   48   63   78  
 [8,]  6   21   36   51   66   81  
 [9,]  9   24   39   54   69   84  
[10,] 12   27   42   57   72   87

In [96]:
x

[,1] [,2] [,3] [,4] [,5] [,6]
[1,]  1   16   31   46   61   76  
[2,]  4   19   34   49   64   79  
[3,]  7   22   37   52   67   82  
[4,] 10   25   40   55   70   85  
[5,] 13   28   43   58   73   88

In [97]:
x[-c(1), -c(1)]

[,1] [,2] [,3] [,4] [,5]
[1,] 19   34   49   64   79  
[2,] 22   37   52   67   82  
[3,] 25   40   55   70   85  
[4,] 28   43   58   73   88

In [98]:
x

[,1] [,2] [,3] [,4] [,5] [,6]
[1,]  1   16   31   46   61   76  
[2,]  4   19   34   49   64   79  
[3,]  7   22   37   52   67   82  
[4,] 10   25   40   55   70   85  
[5,] 13   28   43   58   73   88

In [99]:
1 %in% x

[1] TRUE

In [100]:
2 %in% x

[1] FALSE

In [101]:
dim(x)

[1] 5 6

In [102]:
length(x)

[1] 30

In [103]:
x<- array(seq(from = 0, to = 89, by = 3), dim = c(4, 3, 2))

In [104]:
print(x)

, , 1

     [,1] [,2] [,3]
[1,]    0   12   24
[2,]    3   15   27
[3,]    6   18   30
[4,]    9   21   33

, , 2

     [,1] [,2] [,3]
[1,]   36   48   60
[2,]   39   51   63
[3,]   42   54   66
[4,]   45   57   69



In [105]:
x<- array(seq(from = 0, to = 89, by = 3), dim = c(4, 5, 2))
print(x)

, , 1

     [,1] [,2] [,3] [,4] [,5]
[1,]    0   12   24   36   48
[2,]    3   15   27   39   51
[3,]    6   18   30   42   54
[4,]    9   21   33   45   57

, , 2

     [,1] [,2] [,3] [,4] [,5]
[1,]   60   72   84    6   18
[2,]   63   75   87    9   21
[3,]   66   78    0   12   24
[4,]   69   81    3   15   27



In [106]:
x<- array(seq(from = 0, to = 89, by = 3), dim = c(10, 10, 2))
print(x)

, , 1

      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]    0   30   60    0   30   60    0   30   60     0
 [2,]    3   33   63    3   33   63    3   33   63     3
 [3,]    6   36   66    6   36   66    6   36   66     6
 [4,]    9   39   69    9   39   69    9   39   69     9
 [5,]   12   42   72   12   42   72   12   42   72    12
 [6,]   15   45   75   15   45   75   15   45   75    15
 [7,]   18   48   78   18   48   78   18   48   78    18
 [8,]   21   51   81   21   51   81   21   51   81    21
 [9,]   24   54   84   24   54   84   24   54   84    24
[10,]   27   57   87   27   57   87   27   57   87    27

, , 2

      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]   30   60    0   30   60    0   30   60    0    30
 [2,]   33   63    3   33   63    3   33   63    3    33
 [3,]   36   66    6   36   66    6   36   66    6    36
 [4,]   39   69    9   39   69    9   39   69    9    39
 [5,]   42   72   12   42   72   12   42   72   12    42
 [6,]   45   75 

In [107]:
x<- array(seq(from = 0, to = 89, by = 3), dim = c(5, 3, 2))
print(x)

, , 1

     [,1] [,2] [,3]
[1,]    0   15   30
[2,]    3   18   33
[3,]    6   21   36
[4,]    9   24   39
[5,]   12   27   42

, , 2

     [,1] [,2] [,3]
[1,]   45   60   75
[2,]   48   63   78
[3,]   51   66   81
[4,]   54   69   84
[5,]   57   72   87



In [108]:
x[2, 3, 1] 

[1] 33

In [109]:
x[,c(1),2]

[1] 45 48 51 54 57

In [110]:
x[c(1),,2]

[1] 45 60 75

In [111]:
2 %in% x

[1] FALSE

In [112]:
3 %in% x

[1] TRUE

In [113]:
dim(x)

[1] 5 3 2

In [114]:
x <- c(2, 7, 3, 6, 1)
y <- c(3, 7, 3, 5, 9)

In [115]:
x

[1] 2 7 3 6 1

In [116]:
y

[1] 3 7 3 5 9

In [117]:
rbind(x,y)

[,1] [,2] [,3] [,4] [,5]
x 2    7    3    6    1   
y 3    7    3    5    9

In [118]:
cbind(x,y)

x y
[1,] 2 3
[2,] 7 7
[3,] 3 3
[4,] 6 5
[5,] 1 9

In [119]:
x<- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"))
x

[1] Jazz    Rock    Classic Classic Pop     Jazz    Rock    Jazz   
Levels: Classic Jazz Pop Rock

In [120]:
levels(x) 

[1] "Classic" "Jazz"    "Pop"     "Rock"